CREATE DATABASE property24;

go

create table property_details(
COUNTRY varchar(250),
PROVINCE varchar(250),
CITY varchar(250),
PROPERTY_PRICE int,
BEDROOMS int,
BATHROOMS int,
PARKING int,
FLOOR_SIZE int,
MONTHLY_REPAYMENT int,
TOTAL_ONCE_OFF_COSTS int,
MIN_GROSS_MONTHLY_INCOME INT,

)

go

INSERT INTO dbo.property_details(COUNTRY, PROVINCE, CITY, PROPERTY_PRICE, BEDROOMS, BATHROOMS, PARKING, FLOOR_SIZE, MONTHLY_REPAYMENT, TOTAL_ONCE_OFF_COSTS, MIN_GROSS_MONTHLY_INCOME)

VALUES ( 'SOUTH AFRICA', 'GAUTENG', 'SANDTON', 1375000, 3, 2, 1, 87, 13497, 84538, 44991)


